### ISSUE TITLE
The twelve-factor - Princípios e boas práticas aplicados no mundo real

### ISSUE THREAD

**Issue by linyatis** [MeetupCloudRS/call4papers#4]
Fale sobre você
=========
Engenheiro de software no Grupo Zap, onde, além de programar, já assumi diversos papéis diferentes que vão desde líder de guildas até product owner.

Já fui sócio de uma startup e falhei bastante, mas aprendi que isso faz parte da caminhada e que o importante é “saber falhar”.

####  Seus contatos:

 - Linkedin: https://www.linkedin.com/in/jfilipelyra/
 - Github: https://github.com/linyatis
 - Twitter: https://twitter.com/jfilipelyra

Sobre o que é a talk?
=========
**Título: "The twelve-factor - Princípios e boas práticas aplicados no mundo real"**.

O sucesso no desenvolvimento de software se baseia em boas práticas e simplicidade acima de tudo, não da "melhor linguagem", arquitetura mais "magic-hard-style" e "silver bullets".  
Assim, no Grupo Zap desenvolvemos nossos projetos baseados em Princípios tomando como base o "The 12 factor".  
Nesta apresentação mostrarei por que achamos que os 12 fatores fazem sentido e quais ferramentas e técnicas utilizamos no desenvolvimento da API de anúncios do Grupo Zap.

https://goo.gl/kg475v

Público alvo
=========
Desenvolvedores, arquitetos de software e sysadmins interessados em DevOps e práticas ágeis de desenvolvimento de software.

Qual o nível da talk?
=========
- [x] Intermediário

Referências
========
 - [12 factor official site](https://12factor.net/pt_br/)
 - [Book: Building Microservices (Sam Newman)](http://shop.oreilly.com/product/0636920033158.do)
 - [Talk: The Twelve Factor app: Best Practices for Java Deployment by Joe Kutner](https://youtu.be/94PxlbuizCU)
 - [Blog post: How do you build 12-factor apps using Kubernetes?](https://www.mirantis.com/blog/how-do-you-build-12-factor-apps-using-kubernetes/)

**Comment by marcieltorres** [comment]
Talk efetuada no meetup do dia 29/08/2018
